### ISSUE TITLE
Keine Leistungsmessung, kein Schalten

### ISSUE THREAD

**Issue by quizilkend** [BastiJoe/grindertimer#1]
Guten Morgen,

nachdem ich zuerst traurig festgestellt habe, dass der Grindertimer nicht mehr vertrieben wird, habe ich mit Begeisterung feststellen dürfen, dass es dieses Repo gibt und mir direkt die entsprechende Steckdose geshoppt und geflasht.

Leider funktioniert es bei mir allerdings nicht. Wenn ich mir die Leistung in der App anzeigen lasse, so ist die immer 0 (auch, wenn ich einen Toaster mit ~100W anschließe) und wenn kein Leistungsbezug da ist, schaltet der Timer ja auch nie ein. So bezieht die Mühle nie elektrische Leistung.

Hast du eine Idee, woran das liegen könnte? Kann ich über einen API-Befehl die Steckdose auf *AN* zwingen?

Ich freue mich sehr über eine Rückmeldung!
Samuel

**Comment by BastiJoe** [comment]
Hi Samuel,

die Steckdose ist mit der Firmware immer auf AN. Wenn Leistung gezogen wird, startet der Timer und nach Ablauf schaltet das Relais AUS.

- Welche Hardware hast du gekauft?
- siehst du den Wifi Access Point der Steckdose?
Viele Grüße

Sebastian

**Comment by quizilkend** [comment]
Wow, das ging ja schnell - danke!

Ich habe den hier gebraucht gekauft.
![grafik](https://github.com/user-attachments/assets/f509714a-695a-4e6e-bcfd-16de8b8b4721)


Ich sehe den AP die ganze Zeit, er lässt sich auch nicht ausschalten durch Druck auf den Taster. Die Verbindung zur App klappt tadellos.
Als die Grindertimer Firmware noch nicht geflasht war ließ sich die Steckdose noch gut über den Taster schalten.

**Comment by BastiJoe** [comment]
auf der Unterseite müsste eine Typenbezeichnung stehen. Bitte davon auch mal ein Foto machen. Im worst case haben die die PIN Belegung geändert. Dann kannst du aber noch über den Access Point eine neue Firmware flashen. VG

**Comment by quizilkend** [comment]
Alles klar, mache ich nachher, wenn ich wieder zu Hause bin.
Danke für deine Hilfe!

**Comment by quizilkend** [comment]
So, Foto gemacht.
![PXL_20241015_204804257 MP](https://github.com/user-attachments/assets/52e6b9fb-7dfb-49e4-a964-8a33222c92ac)

Ist zwar etwas unscharf, aber man kann alle Buchstaben entziffern.

**Comment by quizilkend** [comment]
Und, hast du eine Idee?
Wenn ich rausfinde könnte, was die Ports für was sind, kann ich auch den Code anpassen und mit etwas Übung vermutlich auch die *.bin*-Datei zum Flashen bauen.

**Comment by BastiJoe** [comment]
Das Model ist eigentlich richtig.
Nochmal für mich zum Verständnis:
- du hast die .bin mit tuya convert geflasht?
- baut die android app eine verbindung zum gerät auf?
- wenn du ein gerät an die Dose hängst, hat das Gerät dann Strom und läuft ganz normal?
- wenn ja, habe ich verstanden wird in der app aber keine Leistung gemessen/angezeigt?

VG

**Comment by BastiJoe** [comment]
Wenn sonst alles funktioniert und es mit hoher wahrscheinlichkeit an verdrehten pins liegt, kannst du unter
http://192.168.4.1:81/update
die software tasmota flashen.
Damit kannst du dann die pin konfiguration ausprobieren.

**Comment by quizilkend** [comment]
Hi,
3/4 mal ja. Nur, dass kein Elektrisches Gerät Leistung von der Steckdose bezieht, seit ich sie geflasht habe. Davor funktionierte sie.

Dann versuche ich mein Glück am besten mit Tasmota?

**Comment by BastiJoe** [comment]
Also das relais scheint geöffnet zu sein? Das Gerät bekommt an der Dose keinen Strom?
Ja dann am besten mit tasmota gucken wie die pin Belegung ist.
Viele Grüße

**Comment by BastiJoe** [comment]
https://templates.blakadder.com/avatto_JH-G01E.html

**Comment by quizilkend** [comment]
Guten Abend,
ich habe heute noch mal etwas Zeit investiert und es scheint mir leider eher, als ob bei meinem Modell die Leistungsmessung leider einfach nicht funktioniert.
Von daher schließe ich den Issue mal. Danke für die freundliche Hilfe!

**Comment by BastiJoe** [comment]
Ich kann dir noch ein Gerät zuschicken, das aus der charge kommt wo es klappt.
Schick mir bei Interesse eine Mail mit Adresse an
basti.joe@gmail.com
Viele Grüße
